// require('../css/entry.css')
require('../less/entry.less')
require('jquery')
let tool = require('./tool')
var oImg = new Image()
oImg.src = require('../image/2.jpg')
document.body.appendChild(oImg)
tool.hello('hello world 你好世界 你好混蛋 ...')
console.log('头发白了')
console.log($('#img'))
var item1 = require('./item1.js')
var item2 = require('./item2.js')
item1.init()
item2.init()
